---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/currencies":
    get:
      summary: list currencies
      tags:
      - Currency
      description: Get all currencies
      responses:
        '200':
          description: successful
    post:
      summary: create currency
      tags:
      - Currency
      description: Create new Currency
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
              required:
              - name
              - code
  "/currencies/{id}":
    get:
      summary: show currency
      tags:
      - Currency
      description: Get Detail of Single Currency Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    put:
      summary: update currency
      tags:
      - Currency
      description: Update Single Currency Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    delete:
      summary: delete currency
      tags:
      - Currency
      description: Deletes a Single Currency Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:8086
