---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/currencies":
    get:
      summary: list currencies
      tags:
      - Currency
      description: Get all currencies
      responses:
        '200':
          description: successful
    post:
      summary: create currency
      tags:
      - Currency
      description: Create new Currency
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
              required:
              - name
              - code
  "/currencies/{id}":
    get:
      summary: show currency
      tags:
      - Currency
      description: Get Detail of Single Currency Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    put:
      summary: update currency
      tags:
      - Currency
      description: Update Single Currency Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
    delete:
      summary: delete currency
      tags:
      - Currency
      description: Deletes a Single Currency Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/products":
    get:
      summary: list products
      tags:
      - Product
      description: Get all products
      responses:
        '200':
          description: successful
    post:
      summary: create product
      tags:
      - Product
      description: Create new Product against a Store
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
                price:
                  type: string
                  format: decimal
                store_id:
                  type: integer
              required:
              - name
              - code
              - price
              - store_id
  "/products/{id}":
    get:
      summary: show product
      tags:
      - Product
      description: Get Detail of Single Product Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    put:
      summary: update product
      tags:
      - Product
      description: Updates a Single Product Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                code:
                  type: string
                price:
                  type: string
                  format: decimal
                store_id:
                  type: integer
    delete:
      summary: delete product
      tags:
      - Product
      description: Deletes a Single Product Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
  "/products/price_check":
    post:
      summary: price check
      tags:
      - Product
      description: Calculates price for all the items present in cart
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                cart:
                  type: array
                  items:
                    properties:
                      product_id:
                        type: integer
                      quantity:
                        type: integer
  "/stores":
    get:
      summary: list stores
      tags:
      - Store
      description: Get all stores
      responses:
        '200':
          description: successful
    post:
      summary: create store
      tags:
      - Store
      description: Create new Store
      parameters: []
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                currency_id:
                  type: integer
              required:
              - name
              - currency_id
  "/stores/{id}":
    get:
      summary: show store detail along with products
      tags:
      - Store
      description: Get Detail of Single Store Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
    put:
      summary: update store
      tags:
      - Store
      description: Updates a Single Store Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                currency_id:
                  type: integer
    delete:
      summary: delete store
      tags:
      - Store
      description: Deletes a Single Store Record
      parameters:
      - name: id
        in: path
        required: true
        schema:
          type: string
      responses:
        '200':
          description: successful
servers:
- url: http://{defaultHost}
  variables:
    defaultHost:
      default: localhost:8086
